<a href="https://colab.research.google.com/github/Ikunalk4/ml/blob/main/ml_LR(Multi-Variable).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Machine Learning - Linear Regression Multiple Variable(codebasics)

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
import math
miden = df.bedrooms.median()

In [8]:
df.bedrooms = df.bedrooms.fillna(miden)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
model = linear_model.LinearRegression()
model.fit(df.drop('price',axis='columns'),df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
model.predict([[3000,3,10]])

array([595359.7888393])

In [12]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [13]:
model.intercept_

221323.00186540396

model.predict is a testing method, which takes a 2D array

In [14]:
model.predict([[2500,4,5]])

array([578876.03748933])